---
title: 'R Plotting: ggpubr'
author: "Shen, Zhuangfuli, zshen8"
date: "01/07/2018"
output:
  html_document:
    theme: readable
    toc: yes
---

---------------------------------------
```{r setup, echo = FALSE, message = FALSE, warning = FALSE}
options(scipen = 1, digits = 4, width = 80)
```

```{r}
# install.packages("ggpubr")
# From Github
# if(!require(devtools)) install.packages("devtools") devtools::install_github("kassambara/ggpubr")
library(ggpubr)
```
```{r}
# Load Data
set.seed(42)
df <- data.frame(sex=factor(rep(c('m', 'f'), each=1000)), weight=c(rnorm(1000,150,30), rnorm(1000,120,20)))
head(df)
```
```{r}
# Density Distribution Plot
ggdensity(df, x='weight', add='mean',rug=T, color = 'sex', fill='sex',
          pallette=c('#00AFBB', '#E7B800'))
```

```{r}
# Histogram
gghistogram(df, x='weight', add='mean', rug=T, color='sex', fill='sex',
            pallette=c('#00AFBB', '#E7B800'))
```
```{r}
data('ToothGrowth')
df2 <- ToothGrowth
head(df2)
```
```{r}
# Boxplot
p <- ggboxplot(df2, x='dose', y='len', color='dose', add='jitter', shape='dose',
               palette=c('#00AFBB', '#E7B800', '#FC4E07'))
compar <- list(c('0.5', '1'), c('1', '2'), c('0.5', '2'))
p + stat_compare_means(comparisons = compar) + stat_compare_means(label.y=50)
```

```{r}
# Violin
p <- ggviolin(df2, x='dose', y='len', fill='dose', add='boxplot', add.params=list(fill='white'),
              palette=c('#00AFBB', '#E7B800', '#FC4E07'))
p + stat_compare_means(comparisons=compar, label='p.signif') + stat_compare_means(label.y=50)
```

```{r}
data('mtcars')
df3 <- mtcars
df3$cyl <- factor(df3$cyl)
df3$name <- rownames(df3)
head(df3[ ,c('name', 'wt', 'mpg', 'cyl')])
```
```{r}
# Barplot
ggbarplot(df3, x='name', y='mpg', fill='cyl', color='white',
          palette='jco', sort.val='desc', sort.by.groups=F, x.text.angle=60)

ggbarplot(df3, x='name', y='mpg', fill='cyl', color='white',
          palette='jco', sort.val='asc', sort.by.groups=T, x.text.angle=60)
```
```{r}
# 偏差图
df3$mpg_z <- (df3$mpg - mean(df3$mpg))/sd(df3$mpg)
df3$mpg_grp <- factor(ifelse(df3$mpg_z < 0, 'low', 'high'), levels=c('low', 'high'))
head(df3[,c('name', 'wt', 'mpg', 'mpg_grp', 'cyl')])

ggbarplot(df3, x='name', y='mpg_z', fill='mpg_grp', color='white',
          palette='jco', sort.val='asc', sort.by.groups=F, x.text.angle=60,
          ylab='MPG z-score', xlab=F, legend.title='MPG Group')
```
```{r}
# 坐标轴变换
ggbarplot(df3, x='name', y='mpg_z', fill='mpg_grp', color='white', 
          palette='jco', sort.val='desc', sort.by.groups=F, 
          x.text.angle=60, ylab='MPG z-score', xlab=F, 
          legend.title='MPG Group', rotate=T, ggtheme=theme_minimal())
```

```{r}
# Dot Chart

# Lollipop Chart
ggdotchart(df3, x='name', y='mpg', color='cyl', add='segments', sorting='ascending',
          palette=c('#00AFBB', '#E7B800', '#FC4E07'),
          ggtheme=theme_pubr())

ggdotchart(df3, x='name', y='mpg', color='cyl', add='segments', sorting='descending',
           rotate=T, dot.size=5, group='cyl',
           palette=c('#00AFBB', '#E7B800', '#FC4E07'),
           label = round(df3$mpg), font.label=list(color='white', size=6, vjust=0.5),
           ggtheme=theme_pubr())
```
```{r}
# 偏差图
ggdotchart(df3, x='name', y='mpg_z', color='cyl', 
           palette=c('#00AFBB', '#E7B800', '#FC4E07'), 
           sorting="descending", add='segment', add.params=list(color='lightgray', size=2), 
           group='cyl', dot.size=6, label=round(df3$mpg_z, 1), 
           font.label=list(color='white', size=9, vjust=0.5),
           ggtheme=theme_pubr()) + geom_line(yintercept=0, linetype=2, color='lightgray')
```
```{r}
# Cleveland
ggdotchart(df3, x='name', y='mpg', color='cyl',
           palette=c('#00AFBB', '#E7B800', '#FC4E07'),
           sorting='descending', rotate=T, dot.size=2, y.text.col=T,
           ggtheme=theme_pubr()) + theme_cleveland()
```

